# Generated by Django 5.1.6 on 2025-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blogpost_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
